### ISSUE TITLE
Rename the family to "direct-manipulation"/"Direct Manipulation"

### ISSUE THREAD

**Issue by jverkoey** [material-motion-archive/direct-manipulation-swift#10]
Need to rename the:
- [x] repo,
- [ ] podspec,
- [ ] and classes.

**Comment by jverkoey** [comment]
Renamed the repo to https://github.com/material-motion/material-motion-family-direct-manipulation-swift

**Comment by rcameron** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1545
