### ISSUE TITLE
Objective-C usage

### ISSUE THREAD

**Issue by jverkoey** [material-motion-archive/direct-manipulation-swift#16]
- [ ] All class names need to have an `@objc(MDM...)` name mapping.
- [ ] Should include an Objective-C unit test file called "ObjectiveCAPITests.m" that simply instantiates each of the public APIs. These tests are meant to flag any regression in Objective-C support. All other tests can still be written in Swift.

**Comment by rcameron** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1739

**Comment by rcameron** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1739
