### ISSUE TITLE
Move performer logic to private/ dir

### ISSUE THREAD

**Issue by jverkoey** [material-motion-archive/direct-manipulation-swift#19]
All performer logic should be added to swift files in the `src/private` sub-directory.

See the Core Animation family for an example: https://github.com/material-motion/material-motion-family-coreanimation-swift/tree/develop/src/private

**Comment by rcameron** [comment]
Would be worthwhile to mimic the Swift access levels model and call it `src/internal` since performers will most likely be internal?

**Comment by jverkoey** [comment]
Oh! Interesting question. Our `src/private` concept comes from our [Objective-C conventions](https://github.com/material-motion/material-motion-conventions-objc). I could get behind introducing a `src/internal` distinction for swift conventions.

Can you [start a discussion](https://github.com/material-motion/material-motion-team/issues/new) about this on the team repo?

**Comment by jverkoey** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1814
