### ISSUE TITLE
Remove BlockGesturable type

### ISSUE THREAD

**Issue by jverkoey** [material-motion-archive/direct-manipulation-swift#7]
This plan is somewhat too powerful in that it allows arbitrary blocks to be provided to it. This can leak separation of concerns back to the creator of the plan.

Example:

```
BlockGesturable(withGestureRecognizer: gesture) { gesture in
  // Dangerous: access internal state of the registering agent
}
```

**Comment by rcameron** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1545
