### ISSUE TITLE
GesturePerformer likely shouldn't be adding the gesture recognizer to the target

### ISSUE THREAD

**Issue by jverkoey** [material-motion-archive/direct-manipulation-swift#9]
The gesture recognizer may already be added to a view — e.g. the parent view — so we may not want to be calling `target.addGestureRecognizer` ourselves in GesturePerformer.

**Comment by jverkoey** [comment]
Considered this more while writing the spec for Direct Manipulation; the plan's gesture recognizer property can be optional.

If no gesture recognizer is provided, then the performer can create one and add it to the target.

If a gesture recognizer is provided, then we may only want to add the gesture recognizer to the target if it doesn't already have a view.

**Comment by pingpongboss** [comment]
Just want to note that it seems strange to me that the GestureRecognizer is managed by the client and provided to the Draggable Plan.

Seems to me like you'd want to abstract away the GestureRecognizer by having it be privately owned by the Performer.

**Comment by jverkoey** [comment]
If a gesture recognizer already exists then the client needs a way to pass it into the system. For example, iOS provides an edge swipe gesture recognizer on all view controllers.

**Comment by rcameron** [comment]
I was also of the mind that it should be abstracted away, but making it optional seems like the right approach considering the example you provided.

I attempted to turn Gesturable into a protocol requiring a gesture recognizer. I was thinking customized classes such as Draggable could then vend a panGestureRecognizer, which would be a computed property that casts the protocol-required gesture recognizer. I believe this is similar to how the tableView and collectionView properties work on UITVC and UICVC.

**Comment by jverkoey** [comment]
Could the application of swift generics here aid in any way?

**Comment by rcameron** [comment]
🎊 My diff is ready for review at http://codereview.cc/D1620
